version: "3.7"

services:
  rails:
    build: .

    image: "fuminimax-rails:6.0.1"

    init: true

    ports:
      - "3000:3000"

    volumes:
      - rails-volume:/app
      - ./vendor/docker/bundle:/usr/local/bundle
      
    entrypoint: /docker-entrypoint.sh

volumes:
  rails-volume: